include(${CMAKE_CURRENT_LIST_DIR}/Android.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Desktop.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Linux.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MacOS.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Windows.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/WebOS.cmake)

macro(spool_resolve_platform_dependencies)
    if(ANDROID)
        spool_resolve_android_dependencies()
    elseif(SPOOL_WEBOS)
        spool_resolve_webos_dependencies()
    elseif(WIN32)
        spool_resolve_windows_dependencies()
    elseif(APPLE)
        spool_resolve_macos_dependencies()
    else()
        spool_resolve_linux_dependencies()
    endif()
endmacro()

function(spool_configure_platform_targets native_target core_target)
    if(ANDROID)
        spool_configure_android_targets(${native_target} ${core_target})
        return()
    endif()
    if(SPOOL_WEBOS)
        spool_configure_webos_targets(${native_target} ${core_target})
        return()
    endif()

    spool_add_desktop_sources(${native_target} ${core_target})
    if(WIN32)
        spool_configure_windows_targets(${native_target} ${core_target})
    elseif(APPLE)
        spool_configure_macos_targets(${native_target} ${core_target})
    else()
        spool_configure_linux_targets(${native_target} ${core_target})
    endif()
endfunction()

function(spool_import_static_platform_plugins native_target)
    if(ANDROID)
        return()
    elseif(SPOOL_WEBOS)
        spool_import_static_webos_plugins(${native_target})
    else()
        find_library(XKBCOMMON_LIB xkbcommon REQUIRED)
        target_link_libraries(${native_target} PRIVATE ${XKBCOMMON_LIB})
    endif()
endfunction()
