#!/usr/bin/env bash
set -euo pipefail

# VERSION is the one place the release version is set: CMakeLists.txt reads it
# into SPOOL_VERSION and every artifact is named from that. The AUR recipe
# cannot read it -- makepkg parses a literal pkgver, and .SRCINFO is generated
# from the recipe rather than from the tree -- so the number is copied into
# both, and a copy is something that drifts. It did: the recipe sat at 0.7.13
# through two releases, which is a package that installs the wrong version for
# everyone who uses it and fails for nobody here.
#
# The AppStream metainfo carries it a third time, as the newest entry of a
# release history. A desktop reads that to say what is installed and what an
# update would bring, so a missing entry makes a release invisible to the
# software centre even when the binary is right.
#
# usage: check-version-sync.sh [--staged|--rev SHA] [--tag REF]
#   --staged   read the files from the index, for pre-commit
#   --rev SHA  read them from that commit, for a tag that is not HEAD
#   --tag REF  also require refs/tags/vX.Y.Z to match, for pre-push

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE=worktree
REV=""
TAG_REF=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --staged) MODE=--staged; shift ;;
    --rev) MODE=--rev; REV="${2:?--rev needs a commit}"; shift 2 ;;
    --tag) TAG_REF="${2:?--tag needs a ref}"; shift 2 ;;
    *) echo "usage: $0 [--staged|--rev SHA] [--tag REF]" >&2; exit 2 ;;
  esac
done

read_file() {
  case "$MODE" in
    --staged) git -C "$ROOT" show ":$1" 2>/dev/null ;;
    # A tag can name a commit that is not checked out, and it is that commit's
    # files the tag will publish -- not whatever the worktree happens to hold.
    --rev) git -C "$ROOT" show "$REV:$1" 2>/dev/null ;;
    *) cat "$ROOT/$1" 2>/dev/null ;;
  esac
}

VERSION_FILE=VERSION
PKGBUILD=packaging/aur/PKGBUILD
SRCINFO=packaging/aur/.SRCINFO
METAINFO=app/com.sachk.spool.metainfo.xml

version="$(read_file "$VERSION_FILE" | tr -d '[:space:]')"
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: $VERSION_FILE does not hold a version: '${version}'" >&2
  exit 1
fi

fail=0
note() { echo "error: $*" >&2; fail=1; }

pkgbuild="$(read_file "$PKGBUILD")"
if [[ -z "$pkgbuild" ]]; then
  note "$PKGBUILD is missing or empty"
else
  grep -Fqx "pkgver=$version" <<<"$pkgbuild" \
    || note "$PKGBUILD: pkgver is $(grep -m1 '^pkgver=' <<<"$pkgbuild" | cut -d= -f2), expected $version"
fi

# .SRCINFO is generated by makepkg --printsrcinfo, so every one of these is a
# separate expansion of pkgver rather than a reference to it, and each can be
# stale on its own.
srcinfo="$(read_file "$SRCINFO")"
if [[ -z "$srcinfo" ]]; then
  note "$SRCINFO is missing or empty"
else
  grep -Fqx "	pkgver = $version" <<<"$srcinfo" \
    || note "$SRCINFO: pkgver is $(grep -m1 'pkgver = ' <<<"$srcinfo" | sed 's/.*pkgver = //'), expected $version"
  grep -Fqx "	provides = spool=$version" <<<"$srcinfo" \
    || note "$SRCINFO: provides does not say spool=$version"
  # The release asset is named from the version twice over: the tag directory
  # and the tarball. A bump that misses either downloads someone else's build.
  grep -Fq "/download/v$version/Spool-$version-linux-x86_64.tar.zst" <<<"$srcinfo" \
    || note "$SRCINFO: source URL does not point at the v$version tarball"
fi

# The history is newest first, so the release being made is the first entry.
# Checking only that one keeps the older entries as the record they are.
metainfo="$(read_file "$METAINFO")"
if [[ -z "$metainfo" ]]; then
  note "$METAINFO is missing or empty"
else
  newest="$(grep -m1 -o '<release version="[^"]*"' <<<"$metainfo" | sed 's/.*version="//; s/"//')"
  if [[ -z "$newest" ]]; then
    note "$METAINFO has no <release version=\"...\"> entry"
  elif [[ "$newest" != "$version" ]]; then
    note "$METAINFO: newest release entry is $newest, expected $version"
  fi
fi

if [[ -n "$TAG_REF" ]]; then
  tag="${TAG_REF#refs/tags/}"
  # Only release tags claim a version; anything else is free to be named
  # whatever it is for.
  if [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    [[ "$tag" == "v$version" ]] \
      || note "tag $tag does not match $VERSION_FILE ($version)"
  fi
fi

if [[ $fail -ne 0 ]]; then
  echo "" >&2
  echo "The version is set in four places and they disagree. VERSION is the" >&2
  echo "source. Update $PKGBUILD and $METAINFO," >&2
  echo "then regenerate $SRCINFO --" >&2
  echo "tools/update-aur-checksums.sh does the recipe and the .SRCINFO together" >&2
  echo "once the release is published." >&2
  exit 1
fi
