# Bundled providers: the pinned packages in providers/lock.json, unpacked at
# configure time into a Qt resource at qrc:/providers/<id>/. Nothing is
# downloaded here; a digest mismatch stops the configure.
#
# For provider development, SPOOL_PROVIDER_OVERRIDES takes id=/path/to/checkout
# pairs, replacing matching pins and adding providers not present in the lock.

set(SPOOL_PROVIDER_OVERRIDES "" CACHE STRING "id=/path pairs bundling local providers, replacing matching pins")

function(spool_bundle_providers target)
    set(lock "${CMAKE_CURRENT_SOURCE_DIR}/providers/lock.json")
    set(out "${CMAKE_CURRENT_BINARY_DIR}/bundled-providers")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${lock}")
    file(READ "${lock}" json)
    string(JSON count LENGTH "${json}" providers)
    set(pinned_ids "")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON id GET "${json}" providers ${index} id)
            list(APPEND pinned_ids "${id}")
        endforeach()
    endif()
    set(ids ${pinned_ids})
    set(override_ids "")
    set(override_paths "")
    foreach(pair IN LISTS SPOOL_PROVIDER_OVERRIDES)
        if(NOT pair MATCHES "^([a-z][a-z0-9]*([.-][a-z0-9]+)+)=(.+)$")
            message(FATAL_ERROR "Invalid provider override '${pair}'; expected id=/path/to/checkout")
        endif()
        set(id "${CMAKE_MATCH_1}")
        set(path "${CMAKE_MATCH_3}")
        if(id IN_LIST override_ids)
            message(FATAL_ERROR "Duplicate provider override ID: ${id}")
        endif()
        if(NOT IS_ABSOLUTE "${path}" OR NOT EXISTS "${path}/manifest.json")
            message(FATAL_ERROR "Provider override ${id} needs an absolute checkout path with manifest.json: ${path}")
        endif()
        file(READ "${path}/manifest.json" manifest)
        string(JSON manifest_id GET "${manifest}" id)
        if(NOT manifest_id STREQUAL id)
            message(FATAL_ERROR "Provider override ${id} does not match manifest ID ${manifest_id}: ${path}")
        endif()
        list(APPEND override_ids "${id}")
        list(APPEND override_paths "${path}")
        if(NOT id IN_LIST ids)
            list(APPEND ids "${id}")
        endif()
    endforeach()
    set(qrc "<RCC>\n")
    set(digest "")
    foreach(id IN LISTS ids)
        set(root "${out}/${id}")
        set(override "")
        list(FIND override_ids "${id}" override_index)
        if(NOT override_index EQUAL -1)
            list(GET override_paths ${override_index} override)
        endif()
        file(REMOVE_RECURSE "${root}")
        if(override)
            file(GLOB_RECURSE sources CONFIGURE_DEPENDS RELATIVE "${override}"
                "${override}/manifest.json" "${override}/LICENSE" "${override}/NOTICE"
                "${override}/logic/*" "${override}/ui/*" "${override}/assets/*")
            foreach(source IN LISTS sources)
                get_filename_component(directory "${root}/${source}" DIRECTORY)
                file(COPY "${override}/${source}" DESTINATION "${directory}")
                set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${override}/${source}")
            endforeach()
        else()
            list(FIND pinned_ids "${id}" index)
            string(JSON archive GET "${json}" providers ${index} archive)
            string(JSON expected GET "${json}" providers ${index} sha256)
            set(package "${CMAKE_CURRENT_SOURCE_DIR}/providers/${archive}")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${package}")
            file(SHA256 "${package}" actual)
            if(NOT actual STREQUAL expected)
                message(FATAL_ERROR "${package} does not match its pin in providers/lock.json")
            endif()
            file(ARCHIVE_EXTRACT INPUT "${package}" DESTINATION "${root}")
            # Archive times are zeroed for reproducibility; restamp them so rcc
            # sees a changed pin as newer than the resource it built before.
            file(GLOB_RECURSE extracted "${root}/*")
            file(TOUCH_NOCREATE ${extracted})
        endif()
        file(GLOB_RECURSE files RELATIVE "${root}" "${root}/*")
        list(SORT files)
        string(APPEND qrc "  <qresource prefix=\"/providers/${id}\">\n")
        foreach(file IN LISTS files)
            string(APPEND qrc "    <file alias=\"${file}\">${root}/${file}</file>\n")
            file(SHA256 "${root}/${file}" file_digest)
            string(APPEND digest "${id}/${file}:${file_digest}\n")
        endforeach()
        string(APPEND qrc "  </qresource>\n")
    endforeach()
    string(APPEND qrc "</RCC>\n")
    file(CONFIGURE OUTPUT "${out}/providers.qrc" CONTENT "${qrc}" @ONLY)
    qt_add_resources(resources "${out}/providers.qrc")
    target_sources(${target} PRIVATE ${resources})
    # Reproducible builds give every resource the same timestamp, so the QML
    # disk cache cannot tell one bundle from the next; this names the bundle.
    string(SHA256 digest "${digest}")
    string(SUBSTRING "${digest}" 0 12 digest)
    target_compile_definitions(${target} PRIVATE SPOOL_PROVIDER_BUNDLE_DIGEST="${digest}")
    set(SPOOL_PROVIDER_BUNDLE_SOURCES ${resources} PARENT_SCOPE)
endfunction()
